cleaner setup built on thickdrilbl

diff --git a/.local/bin/mounter b/.local/bin/mounter
--- a/.local/bin/mounter
+++ b/.local/bin/mounter
@@ -3,30 +3,40 @@
 # Mounts Android Phones and USB drives (encrypted or not). This script will
 # replace the older `dmenumount` which had extra steps and couldn't handle
 # encrypted drives.
-# TODO: Remove already mounted Android phones from prompt.
 # TODO: Try decrypt for drives in crtypttab
 # TODO: Add some support for connecting iPhones (although they are annoying).
 
-set -e
+IFS='
+'
+# Function for escaping cell-phone names.
+escape(){ echo "$@" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g" ;}
 
 # Check for phones.
-phones="$(simple-mtpfs -l 2>/dev/null | sed "s/^/📱/")"
+phones="$(jmtpfs -l 2>/dev/null | sed "s/^/📱/")"
+mountedphones="$(grep "jmtpfs" /etc/mtab)"
+# If there are already mounted phones, remove them from the list of mountables.
+[ -n "$mountedphones" ] && phones="$(for phone in $phones; do
+	for mounted in $mountedphones; do
+		escphone="$(escape "$phone")"
+		[[ "$mounted" =~ "$escphone" ]] && break 1
+	done && continue 1
+	echo "$phone"
+done)"
+
 # Check for drives.
-lsblkoutput="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
+lsblkoutput="$(sudo -A lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
 # Get all LUKS drives
-allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)" || true
+allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)"
 # Get a list of the LUKS drive UUIDs already decrypted.
-decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")" || true
+decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")"
 # Functioning for formatting drives correctly for dmenu:
 filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}' ; }
 
 # Get only LUKS drives that are not decrypted.
-IFS='
-'
 unopenedluks="$(for drive in $allluks; do
 	uuid="${drive%% *}"
 	uuid="${uuid//-}"	# This is a bashism.
-	for open in $decrypted; do
+	[ -n "$decrypted" ] && for open in $decrypted; do
 		[ "$uuid" = "$open" ] && break 1
 	done && continue 1
 	echo "🔒 $drive"
@@ -39,6 +49,10 @@ normalparts="$(echo "$lsblkoutput"| grep -v crypto_LUKS | grep 'part\|rom\|crypt
 alldrives="$(echo "$phones
 $unopenedluks
 $normalparts" | sed "/^$/d;s/ *$//")"
+
+# Quit the script if a sequential command fails.
+set -e
+
 test -n "$alldrives"
 
 # Feed all found drives to dmenu and get user choice.
@@ -65,15 +79,13 @@ case "$chosen" in
 	💾*)
 		chosen="${chosen%% *}"
 		chosen="${chosen:1}"	# This is a bashism.
+		parttype="$(echo "$lsblkoutput" | grep "$chosen")"
 		attemptmount || getmount
-		partitiontype="$(sudo -A lsblk -no "fstype" "$chosen")"
-        userid="$(id -u)"
-        groupid="$(id -g)"
-		case "$partitiontype" in
-			"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,uid="$userid",gid="$groupid",umask=0000;;
-			*) sudo -A mount "$chosen" "$mp"; sudo -A chown "$userid":"$groupid" "$mp";;
+		case "${parttype##* }" in
+			vfat) sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000 ;;
+			btrfs) sudo -A mount "$chosen" "$mp" ;;
+			*) sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)" ;;
 		esac
-		# sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)"
 		notify-send "💾Drive Mounted." "$chosen mounted to $mp."
 		;;
 
@@ -99,9 +111,9 @@ case "$chosen" in
 	📱*)
 		notify-send "❗Note" "Remember to allow file access on your phone now."
 		getmount
-		chosen="${chosen%%:*}"
-		chosen="${chosen:1}"	# This is a bashism.
-		sudo -A simple-mtpfs -o allow_other --device "$chosen" "$mp"
+		number="${chosen%%:*}"
+		number="${chosen:1}"	# This is a bashism.
+		sudo -A jmtpfs -o allow_other -o fsname="jmtpfs-$(escape "$chosen")" --device "$number" "$mp"
 		notify-send "🤖 Android Mounted." "Android device mounted to $mp."
 		;;
 esac
